### ISSUE TITLE
has_image breaks on Plone 5.0.2

### ISSUE THREAD

**Issue by polyester** [collective/collective.isotope#7]
the statement in https://github.com/collective/collective.isotope/blob/master/src/collective/isotope/browser/templates/isotope.pt#L95 breaks on Plone 5.0.2, apparently because of https://github.com/plone/plone.app.contenttypes/pull/278/files.

Replacing it with item_has_image python:item.getIcon; restores functionality, but not sure that is the canonical way to do that

**Comment by fulv** [comment]
It looks like `item_has_image python:item.getIcon` is the canonical way now.
